name: CI-update-dist

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'prerelease/**'
      - 'release/**'
    paths-ignore:
      - 'dist/**'

permissions:
  contents: read

jobs:
  update-dist:
    # Only run for the Gradle repository; otherwise when users create pull requests from their `main` branch
    # it would erroneously update `dist` on their branch (and the pull request)
    if: github.repository == 'gradle/develocity-provenance-governor-actions'
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .node-version

      - name: Setup Develocity for npm
        uses: gradle/develocity-actions/setup-npm@09247f276f2bc73be8ebd0efced38273412d38d0 #v2.0
        with:
          develocity-injection-enabled: true
          develocity-access-key: >
            develocity-ext-github.grdev.net=${{ secrets.DEVELOCITY_ACCESS_KEY }}
          develocity-url: https://develocity-ext-github.grdev.net

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Build distribution
        run: npm run package

      # Commit and push changes; has no effect if the files did not change
      # Important: The push event will not trigger any other workflows, see
      # https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#commits-made-by-this-action-do-not-trigger-new-workflow-runs
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          commit_author: bot-githubaction <bot-githubaction@gradle.com>
          commit_user_name: bot-githubaction
          commit_user_email: bot-githubaction@gradle.com
          commit_message: '[bot] Update dist directory'
          file_pattern: dist
